version: '3.8'

services:
  mongodb:
    image: docker.io/library/mongo:latest
    container_name: concertron-mongodb
    ports:
      - "27017:27017"

  scrapy:
    image: concertron-scrapy-img
    container_name: concertron-scrapy
    depends_on:
      - mongodb
    volumes:
      - /home/concertron/concertron:/app

  discord-bot:
    image: concertron-discord-img
    container_name: concertron-discord
    depends_on:
      - mongodb
    volumes:
      - /home/concertron/concertron:/app

networks:
  default:
    driver: bridge

