# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entries.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rentries.proto\"\x19\n\tEventTags\x12\x0c\n\x04tags\x18\x01 \x03(\t\"\x1b\n\x0bSupportActs\x12\x0c\n\x04tags\x18\x01 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'entries_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EVENTTAGS']._serialized_start=17
  _globals['_EVENTTAGS']._serialized_end=42
  _globals['_SUPPORTACTS']._serialized_start=44
  _globals['_SUPPORTACTS']._serialized_end=71
# @@protoc_insertion_point(module_scope)
