class TagList:
    def __init__(self):
        self.lists = {
                'classical_music': ['Classical music', 'Neoclassical', 'Orchestra', 'Symfonisch', 'Strijkkwartet', 'Vocaal'],
                'electronic': ['Ambient', 'Deep house', 'Drum & Bass', 'DIP', 'Dub', 'EDM', 'Electro', 'Electro pop', 'Electronic', 'Futuristic', 'House', 'Minimal', 'Nu-disco', 'Synth-pop', 'Synthwave', 'Trap'],
                'folk_blues': ['Americana', 'Bluegrass', 'Blues', 'Country', 'Folk', 'Roots / Americana / Country / Blues'],
                'funk_soul_jazz': ['Funk', 'Funky', 'Fusion jazz', 'Jazz', 'Jazzy', 'Neo-soul', 'Soul', 'Soul / Jazz / Funk', 'Soul-funk', 'Soul-funk-jazz'],
                'heavy': ['Heavy', 'Heavy Metal', 'Metal', 'Metal core', 'Post-hardcore'],
                'hip_hop_rnb': ['Alternative R&B', 'Dutch hip hop', 'Hip hop', 'Hip hop / R&B', 'Hip hop duo', 'R&B', 'Rap', 'Rapper', 'Trap'],
                'pop': ["80's", 'Afrobeats', 'Alt pop', 'Dance pop', 'Eurovision Song Contest', 'Hyper pop', 'J-pop', 'K-Pop', 'Lo-Fi', 'MPB', 'Pop', 'Pop rock', 'Pop sensation', 'Synth-pop', 'TikTok sensation'],
                'rock': ['Alt-folk', 'Alternative', 'Alternative / Indie', 'Alternative R&B', 'Alternative rock', 'Art punk', 'Bedroom pop', 'Blues rock', 'Brit pop', 'Classic-pop', 'Country pop', 'Dream pop', 'Folk rock', 'Glam rock', 'Grunge', 'Hard rock', 'Indie', 'Indie folk', 'Indie pop', 'Indie rock', 'Math Rock', 'New Wave', 'Pop-rock', 'Post-rock', 'Postpunk', 'Psych rock', 'Punk', 'Rock', 'Rock-‘n-roll', 'Shoe gaze', 'Ska', 'Stoner rock'],
                'world_music': ['Afro', 'Afro / Reggae / Dancehall / Latin', 'Afro pop', 'Afrobeat', 'Brazilian', 'Chile', 'Dancehall', 'Desert blues', 'Latin', 'Mali', 'Nigeria', 'Reggae', 'Samba', 'Surinamese', 'Traditional Turkish', 'Turkish'],
                'other': ['Australian', 'Belgium', 'Brass', 'Brazilian', 'Comedian', 'Concert', 'Contemporary', 'Covers', 'Cross-over', 'Disco', 'Down tempo', 'Drag', 'Drummer', 'Duo', 'Dutch', 'Experimental', 'French', 'Genre-bending', 'Harmonic', 'Horror', 'Improv', 'Indiesoul', 'Industrial', 'Ireland', 'Jamaica', 'Krautrock', 'Live After London Calling', 'Live after SSJ', 'Minimal', 'Nederlandstalig', 'Old skool', 'Party', 'Percussion', 'Progressive metal', 'Psychedelic', 'Punk / Noise', 'Queer', 'Rave', 'Rock-‘n-roll', 'Southern', 'Surprise me', 'UK sound', 'Underground', 'Vintage', 'Westcoast', 'blaasinstrumenten', 'blues-roots-americana', 'dance', 'experimental', 'familie', 'filmmuziek', 'funk-jazz', 'global', 'heavy', 'hiphop', 'indie', 'jazz', 'jeugd', 'kamermuziek', 'kennis', 'klassiek', 'metal-punk-heavy', 'midden-oosten-noord-afrika', 'minimal-music', 'nederlands', 'neoklassiek', 'nieuwe-muziek', 'orgel', 'oude-muziek', 'overig', 'piano', 'pop-2', 'pop-electronic', 'pop-global', 'pop-hiphop-rnb', 'reggae-ska', 'riot grrrl', 'roots', 'singer-songwriter', 'singer-songwriter / folk', 'strijkkwartet', 'turks', 'urban-hiphop-rnb', 'urban-soul', 'viool-altviool-cello'],
                }
